<template>
  <div>
    <div>
      <div
        class="
          w-full
          relative
          bg-img-height
          items-center
          justify-center
          xl:flex
          hidden
        "
      >
        <img
          loading="lazy"
          src="https://cdn.tuk.dev/assets/templates/foodies/menu-hero.png"
          class="w-full h-full absolute"
        />
        <button
          class="
            text-5xl text-white
            rounded-lg
            bg-color-orange
            px-14
            py-2
            relative
            hover:opacity-90
          "
        >
          MENU CARD
        </button>
      </div>
    </div>
    <div
      class="
        w-full
        relative
        flex
        items-center
        justify-center
        xl:hidden
        md:h-64
        h-32
        xl:pt-16
        pt-0
      "
    >
      <img
        loading="lazy"
        src="https://cdn.tuk.dev/assets/templates/foodies/menu-hero.png"
        class="w-full h-full absolute"
      />
      <button
        class="
          text-base text-white
          rounded-lg
          bg-color-orange
          px-6
          py-2
          relative
          hover:opacity-90
        "
      >
        MENU CARD
      </button>
    </div>
  </div>
</template>
